name: 2 wakatime stats

on:
  push:
    branches: [ "main" ]
  schedule: [{cron: "0 * * * *"}]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    
      - name: Merge the stats with prefix & postfix string
        run: |
          stats=$(curl -X GET "https://shitdev.nl/api/wakatime_text?username=userexe&editors=6&languages=6")
          echo -e "\`\`\`console\n\$ stats\n${stats}\n\`\`\`"
          echo -e "\`\`\`console\n\$ stats\n${stats}\n\`\`\`" > STATS.md
      - name: Compile the 2.md file
        run: |
          cat NEOFETCH.md STATS.md > 2.md
      - name: Commit & Push changes
        run: |
          git config --global user.name 'Auto'
          git config --global user.email 'auto@example.com'
          git add .
          git commit -am 'Update wakatime stats [Skip Github Action]' --allow-empty || true
          git push
