name: 5 image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  schedule: [{cron: "0 * * * *"}]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v2
      
      - name: generate snake images
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: mrhappyma
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: master
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
