name: refresh

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  refresh:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    
      - uses: actions/checkout@v2
      
      - name: Change out the README.md file
        run: |
          ID=$(curl -X GET "http://www.randomnumberapi.com/api/v1.0/random?min=1&max=5")
          cat ${ID}.md > README.md 
          
      - name: Commit & Push changes
        run: |
          git config --global user.name 'Auto'
          git config --global user.email 'auto@example.com'
          git add .
          git commit -am 'Automatic update [Skip Github Action]' --allow-empty|| true
          git push
